### ISSUE TITLE
Recommend an alternative for this project

### ISSUE THREAD

**Issue by displague** [linode/velero-plugin#6]
This plugin has not been actively maintained. Velero users should be able to use the CSI plugin instead.

Deprecate this project and refer to an alternative when possible.

Depends on:
- https://github.com/linode/linode-blockstorage-csi-driver/issues/107
- https://github.com/vmware-tanzu/velero-plugin-for-csi

**Comment by displague** [comment]
If anyone at Linode sees this and is interested in moving the project to the Linode org -- I'm game.

**Comment by luthermonson** [comment]
@displague i got you fam

**Comment by luthermonson** [comment]
you can archive and point to https://github.com/linode/velero-plugin ill get some moving day and housekeeping PRs up soon

**Comment by displague** [comment]
@luthermonson I've created a transfer to your personal org. From there, you should be able to move it to Linode.

**Comment by luthermonson** [comment]
Now housed at linode/velero-plugin for everyone’s enjoyment

**Comment by mzimry** [comment]
@luthermonson , as Linode SCI Driver is not supporting snapshots, how can one use this plugin in LKE ?
